Formatting changes
interpretml/DiCE pull request #157
Opened 2021-06-06 20:50 UTC by soundarya98

Minor formatting edits: Changed `if(X)` to `if X`

2021-06-07 16:10 UTC, gaugup commented on dice_ml/model.py
> +        if (model is None) and (model_path == ''):
Probably you could drop these parenthesis as well. See the operator precedence order in the list at the link https://data-flair.training/blogs/python-operator-precedence/#:~:text=Python%20Operator%20Precedence%20%E2%80%93%20Short%20Circuiting%20Python%20always,the%20second%20operand%20only%20until%20it%20is%20needed.

2021-06-07 16:11 UTC, gaugup commented on dice_ml/explainer_interfaces/dice_tensorflow2.py
> +            if (itr % self.project_iter) == 0:
Probably you could drop these parenthesis as well. See the operator precedence order in the list at the link https://data-flair.training/blogs/python-operator-precedence/#:~:text=Python%20Operator%20Precedence%20%E2%80%93%20Short%20Circuiting%20Python%20always,the%20second%20operand%20only%20until%20it%20is%20needed.

2021-06-07 16:11 UTC, gaugup commented on dice_ml/explainer_interfaces/dice_tensorflow1.py
> +            if (itr % self.project_iter) == 0:
Probably you could drop these parenthesis as well. See the operator precedence order in the list at the link https://data-flair.training/blogs/python-operator-precedence/#:~:text=Python%20Operator%20Precedence%20%E2%80%93%20Short%20Circuiting%20Python%20always,the%20second%20operand%20only%20until%20it%20is%20needed.

2021-06-07 16:12 UTC, gaugup commented on dice_ml/explainer_interfaces/dice_pytorch.py
> +            if (itr % self.project_iter) == 0:
Probably you could drop these parenthesis as well. See the operator precedence order in the list at the link https://data-flair.training/blogs/python-operator-precedence/#:~:text=Python%20Operator%20Precedence%20%E2%80%93%20Short%20Circuiting%20Python%20always,the%20second%20operand%20only%20until%20it%20is%20needed.

2021-06-07 16:12 UTC, gaugup commented on dice_ml/data_interfaces/public_data_interface.py
>                  for mx in range(len(modes)):
Probably you could drop these parenthesis as well. See the operator precedence order in the list at the link https://data-flair.training/blogs/python-operator-precedence/#:~:text=Python%20Operator%20Precedence%20%E2%80%93%20Short%20Circuiting%20Python%20always,the%20second%20operand%20only%20until%20it%20is%20needed.

2021-06-07 16:13 UTC, gaugup requested changes
See the operator precedence order in the list at the link https://data-flair.training/blogs/python-operator-precedence/#:~:text=Python%20Operator%20Precedence%20%E2%80%93%20Short%20Circuiting%20Python%20always,the%20second%20operand%20only%20until%20it%20is%20needed.

2021-06-21 11:23 UTC, amit-sharma approved these changes

2021-06-21 11:23 UTC, merged